[package]
name = "petname"
version = "1.0.13"
authors = ["Gavin Panella <gavinpanella@gmail.com>"]
edition = "2018"
description = "Generate human readable random names. Usable as a library and from the command-line."
readme = "README.md"
repository = "https://github.com/allenap/rust-petname"
license = "Apache-2.0"
categories = ["command-line-utilities"]
keywords = ["pet", "name", "rand", "random", "generator"]

[badges]
travis-ci = { repository = "allenap/rust-petname", branch = "master" }

[lib]
name = "petname"
path = "src/lib.rs"

[[bin]]
name = "petname"
path = "src/main.rs"
doc = false
required-features = ["clap", "std_rng", "default_dictionary"]

[features]
default = ["std_rng", "default_dictionary"]
# Allows generating petnames with thread rng.
std_rng = ["rand/std", "rand/std_rng"]
# Allows the default dictionary to be used.
default_dictionary = []

[dependencies]
clap = { version = "^2.33.0", default-features = false, optional = true }
itertools = { version = "^0.9.0", default-features = false }
rand = { version = "^0.8.0", default-features = false }
