[package]
name = "petname"
version = "0.1.2"
authors = ["Gavin Panella <gavinpanella@gmail.com>"]
description = "Generate human readable random names."
homepage = "https://github.com/allenap/rust-petname"
license = "Apache-2.0"
readme = "README.md"

[lib]
name = "petname"
path = "src/lib.rs"

[[bin]]
name = "petname"
path = "src/main.rs"
doc = false

[dependencies]
clap = "^2.24.2"
rand = "^0.3.15"
